In [ ]:
import cv2
import numpy as np
from PIL import Image, ImageDraw


# image = Image.open ('board.jpg')

# rad = 100
# circle = Image.new ('L', (rad * 2, rad * 2), 0)
# draw = ImageDraw.Draw (circle)
# draw.ellipse ((0, 0, rad * 2, rad * 2), fill = 255)
# alpha = Image.new ('L', image.size, 255)
# w, h = image.size
# alpha.paste (circle.crop ((0, 0, rad, rad)), (0, 0))
# alpha.paste (circle.crop ((0, rad, rad, rad * 2)), (0, h-rad))
# alpha.paste (circle.crop ((rad, 0, rad * 2, rad)), (w-rad, 0))
# alpha.paste (circle.crop ((rad, rad, rad * 2, rad * 2)), (w-rad, h-rad))
# image.putalpha (alpha)
# image.save ('board1.png')

image = cv2.imread('board.png')

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blur = cv2.medianBlur(gray, 5)
sharpen_kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
sharpen = cv2.filter2D(blur, -1, sharpen_kernel)

thresh = cv2.threshold(sharpen,160,255, cv2.THRESH_BINARY_INV)[1]
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
close = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel, iterations=2)

cnts = cv2.findContours(close, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = cnts[0] if len(cnts) == 2 else cnts[1]

min_area = 100
max_area = 1500
image_number = 0
# print(cnts)
for c in cnts:
    print(c)
    area = cv2.contourArea(c)
#     if area > min_area and area < max_area:
    x,y,w,h = cv2.boundingRect(c)
    ROI = image[y:y+h, x:x+h]
    cv2.imwrite('ROI_{}.png'.format(image_number), ROI)
    cv2.rectangle(image, (x, y), (x + w, y + h), (36,255,12), 2)
    image_number += 1

cv2.imshow('sharpen', sharpen)
cv2.imshow('close', close)
cv2.imshow('thresh', thresh)
cv2.imshow('image', image)
cv2.waitKey()

[[[  0   0]]

 [[  0 599]]

 [[596 599]]

 [[596   0]]]
